FROM nginx

#--[ utils ]
RUN apt-get update
RUN apt-get install -y telnet apache2-utils

#--[ uid mappings ]
RUN groupmod -g $www_data_gid$ www-data
RUN usermod -u $www_data_uid$ www-data

RUN groupmod -g $nginx_gid$ nginx
RUN usermod -u $nginx_uid$ nginx

#--[ entrypoint & cmd ]

COPY ./entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/bin/bash","--login"]
